### ISSUE TITLE
In ProjectList

### ISSUE THREAD

**Issue by misbell** [brunogb/SwiftUIExamples#1]
replace the beta 1 code with this code

            .navigationBarItems(trailing:
                HStack(alignment: .center, spacing: 20){
  
                    Button (action: {
                        self.projectData.insertRandomProject()
                    }) {
                        Image(systemName: "plus")
                                                  .font(.title)
                    }
                    PresentationButton(destination: ProjectWizard()) {
                        Image(systemName: "person.crop.square")
                                                 .font(.title)
                    }
                    
                
                
            }

**Comment by brunogb** [comment]
Just updated it :) thanks!
